name: Docker Build and Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Build and Push Docker Image
        env:
          CLIENT_ID: ${{ steps.azure_login.outputs.client_id }}
          CLIENT_SECRET: ${{ steps.azure_login.outputs.client_secret }}
        run: |
          docker build -t img_webui:v1.0.0 .
          echo $CLIENT_SECRET | docker login -u $CLIENT_ID --password-stdin djibyacr.azurecr.io
          docker tag img_webui:v1.0.0 djibyacr.azurecr.io/img_webui:v1.0.0
          docker push djibyacr.azurecr.io/img_webui:v1.0.0

      - name: Login to Azure
        id: azure_login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}